/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.ConfigureASystem;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.network.Country;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.ArrayList;
import Business.network.State;
import Business.network.City;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import Business.MyJPanel;
import de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel;
/**
 *
 * @author Alienware
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    static int  i = 0;
    private ArrayList<Enterprise> allenterprise;
        MyJPanel imageJPanel;
        int index;
        String[] path = {
                "src/images/home.jpg",
                "src/images/homeless-1.jpg",
                "src/images/homeless.jpg",
                "src/images/homeless27n-3-web.jpg",
                "src/images/img94joktmu7790.jpg",
                "src/images/maxresdefault.jpg"
               // new ImageIcon("src/images/4.jpg"),
              //  new ImageIcon("src/images/5.jpg"),
               // new ImageIcon("src/images/6.jpg"),
               // new ImageIcon("src/images/7.jpg"),
               // new ImageIcon("src/images/8.jpg"),
            };
        
    
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setBounds(200,30,1000,800);
        system =  ConfigureASystem.configure();
        system = dB4OUtil.retrieveSystem();
        imageJPanel = new MyJPanel();
        System.out.println(path.length);

        //container.add(imageJPanel);
           
       /*     this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);
            this.setTitle("windows");
            this.setVisible(true);
       */
       
            Timer timer = new Timer(1000,new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   // System.out.println(i);
                        ImageIcon icon = new ImageIcon(path[i]);
                        //System.out.println(path[i]);
                        icon.setImage(icon.getImage().getScaledInstance(800,600,Image.SCALE_DEFAULT));
                        shabi.setIcon(icon);
                        i++;
                        if(i == path.length-1)
                            i=0;                 
                     }
            });
            timer.start();
            
            

    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        mainJPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PicjPanel = new javax.swing.JPanel();
        shabi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Password:");

        jLabel1.setText("User Name:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnLogin)
                .addGap(46, 46, 46)
                .addComponent(btnLogout)
                .addContainerGap(442, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setLayout(new java.awt.CardLayout());

        mainJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Libian SC", 0, 48)); // NOI18N
        jLabel4.setText("Welcome to the    ");
        mainJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Libian SC", 0, 48)); // NOI18N
        jLabel3.setText(" Homeless Reporting System");
        mainJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        PicjPanel.setBackground(new java.awt.Color(102, 102, 102));
        PicjPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PicjPanelMouseClicked(evt);
            }
        });
        PicjPanel.setLayout(new java.awt.BorderLayout());
        mainJPanel.add(PicjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 250));

        shabi.setForeground(new java.awt.Color(255, 255, 255));
        shabi.setText(" ");
        mainJPanel.add(shabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 700, 470));

        container.add(mainJPanel, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        // Get user name
        
        String userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system user account directory if you have the user
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        //Country inNetwork = null;
       // System.out.println(1);
                this. allenterprise = new ArrayList<>();
        for(Country c:system.getCountryList()){
            for(State s:c.getStatelist()){
                for(City city:s.getCitylist()){
                    for (Enterprise e:city.getEnterprisedirectory().getEnterpriselist() ){
                        allenterprise.add(e);
                    }
                         
                }
            }
        }
        if (userAccount == null) {
           // System.out.println(2);
            //Step2: Go inside each network to check each enterprise
           /* for (Country country : system.getCountryList()) {
                System.out.println(3);
                for (State state :country.getStatelist()){
                    System.out.println(4);
                    for (City city: state.getCitylist()){
                        System.out.println(5);*/
            
                for (Enterprise enterprise : allenterprise) {
                    //System.out.println(6);
                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    if (userAccount == null) {
                        //Step3: Check against each organization inside that enterprise
                      //  System.out.println(7);
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                           // System.out.println(8);
                            userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                               // System.out.println(9);
                                inEnterprise = enterprise;
                                inOrganization = organization;
                                //inNetwork = country;
                                break;
                            }
                        }
                    } else {
                       // System.out.println(10);
                        inEnterprise = enterprise;
                        break;
                    }
                    if (inOrganization != null) {
                       // System.out.println(11);
                        break;
                    }
                
            }
        //}}}
                
                //Step 2-a: Check against each enterprise
                //break;
            
        }

        if (userAccount == null) {
            
          //  System.out.println(13);
            JOptionPane.showMessageDialog(null, "Username/Password pair does not found!");
            return;
        } else {
           // System.out.println(14);
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, system));
            layout.next(container);
            //System.out.println(inEnterprise);
        }
        btnLogin.setEnabled(false);
        btnLogout.setEnabled(true);
        userNameJTextField.setEnabled(false);
        passwordField.setEnabled(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        btnLogout.setEnabled(false);
        userNameJTextField.setEnabled(true);
        passwordField.setEnabled(true);
        btnLogin.setEnabled(true);

        userNameJTextField.setText("");
        passwordField.setText("");

        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("mainJPanel", mainJPanel);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void PicjPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PicjPanelMouseClicked
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_PicjPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try
            {
              javax.swing.UIManager.setLookAndFeel(new SyntheticaBlueLightLookAndFeel());
              //Another way is to use the #setLookAndFeel method of the SyntheticaLookAndFeel class
              //SyntheticaLookAndFeel.setLookAndFeel(String className, boolean antiAlias, boolean useScreenMenuOnMac);
            }
            catch (Exception e)
            {
              e.printStackTrace();
            }
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PicjPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel shabi;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
