/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.UserWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import java.util.ArrayList;


import Business.Organization.Organization;
import Business.WorkQueue.DonateWorkRequest;
import Business.network.City;
import Business.network.Country;
import Business.network.State;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
/**
 *
 * @author linke
 */
public class DonateJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private Organization organization;
    private ArrayList<Organization> typeorganization;
    private ArrayList<Organization> allorganization;
    private ArrayList<City> allcity;
    private City city;
    /**
     * Creates new form DonateJPanel
     */
    public DonateJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account; 
        this.typeorganization = new ArrayList<>();
        this.allorganization = new ArrayList<>();
        this.allcity = new ArrayList<>();
        this.city = enterprise.getCity();
         /*       for(Country country: system.getCountryList()){
            for (State state :country.getStatelist()){
                for(City c:state.getCitylist()){
                    allcity.add(c);
                    
                }
            }
        }*/
                
     
            for(Enterprise e:city.getEnterprisedirectory().getEnterpriselist()){
                for(Organization o:e.getOrganizationDirectory().getOrganizationList()){
                    allorganization.add(o);       
                }
            }
        
        
        populateOrganizationtypeComboBox();
    }


    
private void populateOrganizationtypeComboBox(){
        cbxorganizationtype.removeAllItems();
         
            for(Enterprise e:city.getEnterprisedirectory().getEnterpriselist()){
                if(e.getEnterprisetype().equals(EnterpriseType.Institute))
                {
                    for(Organization o:e.getOrganizationDirectory().getOrganizationList()){
                        cbxorganizationtype.addItem(o.getClass().getSimpleName());   
                        System.out.println(o.getClass().getSimpleName());
                    }
                }
            }
        
//            if(o.getClass().getSimpleName().equals(type)){
//                typeorganization.add(o);
//                
//            }
//        }         
//        for (Organization organization : typeorganization){
//            cbxorganizationname.addItem(organization);
//        }
        
    }
    private void populateOrganizationnameComboBox(String type){
        cbxorganizationname.removeAllItems();
        for(Organization o:allorganization){
            if(o.getClass().getSimpleName().equals(type)){
                cbxorganizationname.addItem(o);
            }
        }
           
        
    }
    
    private void populateItemNameComboBox(String type){
            cbxItemName.removeAllItems();
            System.out.println(type);
        if(type.equals("FoodInstitute")){
            cbxItemName.addItem("Egg");
            cbxItemName.addItem("Bread");
            cbxItemName.addItem("Water");
        }
        else if(type.equals("ClothInstitute")){
            cbxItemName.addItem("Boy Clothes");
            cbxItemName.addItem("Male Clothes");
            cbxItemName.addItem("Aged-male Clothes");
            cbxItemName.addItem("Girl Clothes");
            cbxItemName.addItem("Female Clothes");
            cbxItemName.addItem("Aged-female Clothes");
        }
        else{
            cbxItemName.addItem("Male Shelter");
            cbxItemName.addItem("Female Shelter");
        }
        
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndonate = new javax.swing.JToggleButton();
        cbxorganizationtype = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxorganizationname = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbxItemName = new javax.swing.JComboBox();
        enterpriseLabel = new javax.swing.JLabel();

        btndonate.setText("Donate ");
        btndonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonateActionPerformed(evt);
            }
        });

        cbxorganizationtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FoodInstitute", "ClothInstitute", "ShelterInstitute" }));
        cbxorganizationtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxorganizationtypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Organization Type");

        jLabel2.setText("Organization Name");

        cbxorganizationname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxorganizationnameActionPerformed(evt);
            }
        });

        jLabel3.setText("DonateQuantity");

        txtquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantityActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Donate Item Name");

        cbxItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxItemNameActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("User Donate Work Area:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndonate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxorganizationname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxorganizationtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxItemName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtquantity)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(305, 305, 305)))
                .addGap(0, 170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxorganizationtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxorganizationname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndonate)
                    .addComponent(backJButton))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonateActionPerformed
        // TODO add your handling code here:
        if(txtquantity.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please write the quantity!");
        
            return;
        }
        int quantity = Integer.parseInt(txtquantity.getText());
        
        DonateWorkRequest dwr = new DonateWorkRequest();
        String itemname = (String) cbxItemName.getSelectedItem();
        dwr.setItemName(itemname);
        dwr.setQuantity(quantity);
        dwr.setSender(userAccount);
        dwr.setStatus("Sent");
        dwr.setType("donate");
        Organization donateo = (Organization) cbxorganizationname.getSelectedItem();
        
        donateo.getWorkQueue().getWorkRequestList().add(dwr);
        
        JOptionPane.showMessageDialog(null, "Donate Successfully");
        
        
    }//GEN-LAST:event_btndonateActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void cbxorganizationnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxorganizationnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxorganizationnameActionPerformed

    private void cbxorganizationtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxorganizationtypeActionPerformed

        String organizationtype =  (String)cbxorganizationtype.getSelectedItem();
        
        if (organizationtype != null){
            populateOrganizationnameComboBox(organizationtype);
            populateItemNameComboBox(organizationtype);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cbxorganizationtypeActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cbxItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxItemNameActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_cbxItemNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JToggleButton btndonate;
    private javax.swing.JComboBox cbxItemName;
    private javax.swing.JComboBox cbxorganizationname;
    private javax.swing.JComboBox<String> cbxorganizationtype;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
