/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.UserWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.Police;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ReportWorkRequest;
import javax.swing.JPanel;
import java.util.ArrayList;
import Business.EcoSystem;
import Business.MapsData;
import Business.network.City;
import Business.network.Country;
import Business.network.State;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author liulei
 */
public class ReportJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private Police police;
    private ArrayList<Organization> allorganization;
    private ArrayList<City> allcity;
    private ArrayList<String> comboboxitem;
    /**
     * Creates new form ReportJPanel
     */

    ReportJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = business;
        this.allorganization = new ArrayList<>();
        this.allcity = new ArrayList<>();
        this.comboboxitem = new ArrayList<>();
        
        
        for(Country country: system.getCountryList()){
            for (State state :country.getStatelist()){
                for(City c:state.getCitylist()){
                    allcity.add(c);
                    
                }
            }
        }
        for(City city :allcity){
            for(Enterprise e:city.getEnterprisedirectory().getEnterpriselist()){
                for(Organization o:e.getOrganizationDirectory().getOrganizationList()){
                    allorganization.add(o);       
                }
            }
        }
        
        valueLabel.setText(userAccount.getUsername());
        
        labelclothname.setVisible(false);
        labelclothquantity.setVisible(false);
        labelfoodname.setVisible(false);
        labelshelterquantity.setVisible(false);
        txtClothQuantity.setVisible(false);
        txtFoodQuantity.setVisible(false);
       clothNameComboBox.setVisible(false);
       foodNameComboBox.setVisible(false);
        labelfoodquantity.setVisible(false);
       foodNameComboBox.setVisible(false);
       txtShelterQuantity.setVisible(false);
        //System.out.println(enterprise);
        //valueLabel.setText(enterprise.getName());
        populateComboBoxx();
        populateFoodNameComboBox();
    }
    
    private void populateComboBoxx(){
        clothNameComboBox.removeAllItems();
        foodNameComboBox.removeAllItems();
        conditionCBX.removeAllItems();
        genderCBX.removeAllItems();
        clothNameComboBox.addItem("Boy Clothes");
        clothNameComboBox.addItem("Male Clothes");
        clothNameComboBox.addItem("Aged-male Clothes");
        clothNameComboBox.addItem("Girl Clothes");
        clothNameComboBox.addItem("Female Clothes");
        clothNameComboBox.addItem("Aged-female Clothes");
        conditionCBX.addItem("Bad");
        conditionCBX.addItem("Terrible");
        conditionCBX.addItem("Very Terrible");
        genderCBX.addItem("Male");
        genderCBX.addItem("Female");
    }

    private void populateFoodNameComboBox(){
        foodNameComboBox.removeAllItems();
        foodNameComboBox.addItem("Egg");
        foodNameComboBox.addItem("Bread");
        foodNameComboBox.addItem("Water");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelshelterquantity = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtrace = new javax.swing.JTextField();
        txtfacenumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        cbxShelter = new javax.swing.JCheckBox();
        cbxClothes = new javax.swing.JCheckBox();
        cbxFood = new javax.swing.JCheckBox();
        backJButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        labelclothname = new javax.swing.JLabel();
        labelfoodname = new javax.swing.JLabel();
        clothNameComboBox = new javax.swing.JComboBox<>();
        foodNameComboBox = new javax.swing.JComboBox<>();
        labelclothquantity = new javax.swing.JLabel();
        labelfoodquantity = new javax.swing.JLabel();
        txtShelterQuantity = new javax.swing.JTextField();
        txtClothQuantity = new javax.swing.JTextField();
        txtFoodQuantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtstreetnum = new javax.swing.JTextField();
        txtstreetname = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtcountry = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        btnmap = new javax.swing.JButton();
        conditionCBX = new javax.swing.JComboBox<>();
        genderCBX = new javax.swing.JComboBox<>();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, -1, 40));

        jLabel2.setText("Homeless Information:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel3.setText("First Name*:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel4.setText("Last Name*:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel5.setText("Age*:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel6.setText("Gender:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jLabel7.setText("Race:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        jLabel8.setText("Condition:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        labelshelterquantity.setText("Quantity*");
        add(labelshelterquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 114, -1));

        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });
        add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 114, -1));

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtageKeyTyped(evt);
            }
        });
        add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 114, -1));

        txtrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtraceActionPerformed(evt);
            }
        });
        add(txtrace, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 114, -1));

        txtfacenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfacenumberActionPerformed(evt);
            }
        });
        txtfacenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfacenumberKeyTyped(evt);
            }
        });
        add(txtfacenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 114, -1));

        jLabel10.setText("Height:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        txtHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHeightKeyTyped(evt);
            }
        });
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 114, -1));

        cbxShelter.setText("Shelter");
        cbxShelter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxShelterActionPerformed(evt);
            }
        });
        add(cbxShelter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        cbxClothes.setText("Clothes");
        cbxClothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClothesActionPerformed(evt);
            }
        });
        add(cbxClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        cbxFood.setText("Food");
        cbxFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFoodActionPerformed(evt);
            }
        });
        add(cbxFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, -1));

        jLabel11.setText("Face Number*:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        labelclothname.setText("Cloth Name");
        add(labelclothname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        labelfoodname.setText("Food Name");
        add(labelfoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        clothNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(clothNameComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        foodNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        foodNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodNameComboBoxActionPerformed(evt);
            }
        });
        add(foodNameComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        labelclothquantity.setText("Quantity*");
        add(labelclothquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        labelfoodquantity.setText("Quantity*");
        add(labelfoodquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 60, 20));

        txtShelterQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShelterQuantityActionPerformed(evt);
            }
        });
        txtShelterQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtShelterQuantityKeyTyped(evt);
            }
        });
        add(txtShelterQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 120, -1));

        txtClothQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClothQuantityActionPerformed(evt);
            }
        });
        txtClothQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClothQuantityKeyTyped(evt);
            }
        });
        add(txtClothQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 120, -1));

        txtFoodQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoodQuantityActionPerformed(evt);
            }
        });
        txtFoodQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFoodQuantityKeyTyped(evt);
            }
        });
        add(txtFoodQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 120, -1));

        jLabel9.setText("Address2:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));
        add(txtstreetnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 80, -1));
        add(txtstreetname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 160, -1));
        add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 80, -1));
        add(txtcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 80, -1));
        add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 80, -1));

        btnmap.setText("Maps");
        btnmap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmapActionPerformed(evt);
            }
        });
        add(btnmap, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 100, 40));

        conditionCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(conditionCBX, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 110, -1));

        genderCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(genderCBX, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 110, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("User Report Work Area:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 280, 30));

        jLabel12.setText("Address1:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtraceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtraceActionPerformed

    private void txtfacenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfacenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfacenumberActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(txtfname.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input all neccessary value");
        }
        else if(txtlname.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input all neccessary value");
        }
        else if(txtage.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input all neccessary value");
        }
        else if(txtfacenumber.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input all neccessary value");
        }
        else if(txtfacenumber.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input all neccessary value");
        }
        else if(cbxFood.isSelected()&&txtFoodQuantity.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input all neccessary value");
        }
        else if(cbxClothes.isSelected()&&txtClothQuantity.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input all neccessary value");
        }
        else if(cbxShelter.isSelected()&&txtShelterQuantity.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input all neccessary value");
        }
        else{
        
        if(txtHeight.getText().equals("")){
            txtHeight.setText(null);
        }
        if(txtrace.getText().equals("")){
            txtrace.setText(null);
        }
        String fname = txtfname.getText();
        String lname = txtlname.getText();
        int age = Integer.parseInt(txtage.getText());
        String gender = (String) genderCBX.getSelectedItem();
        String race = txtrace.getText();
        String condition = (String) conditionCBX.getSelectedItem();
        int facenumbber = Integer.parseInt(txtfacenumber.getText());
        String height = txtHeight.getText();
        Boolean clothes = true;
        int streetnum = Integer.parseInt(txtstreetnum.getText());
        String streetname = txtstreetname.getText();
        String city = txtcity.getText();
        String state = txtstate.getText();
        String country = txtcountry.getText();
        if (cbxClothes.isSelected()){
            
        }else{
            clothes = false;
        }
        Boolean food = true;
        if (cbxFood.isSelected()){
            
        }else{
            food = false;
        }
        Boolean shelter = true;
        if (cbxShelter.isSelected()){
            
        }else{
            shelter = false;
        }
        
        MapsData mapsdata = new MapsData();
        mapsdata.setStreetnum(streetnum);
        mapsdata.setStreetname(streetname);
        mapsdata.setCity(city);
        mapsdata.setState(state);
        mapsdata.setCountry(country);
        
        ReportWorkRequest request = new ReportWorkRequest();
        request.setFirstname(fname);
        request.setLastname(lname);
        request.setAge(age);
        request.setHeight(height);
        request.setGender(gender);
        request.setRace(race);
        request.setCondition(condition);
        request.setFacenumber(facenumbber);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setClothes(clothes);
        request.setFood(food);
        request.setShelter(shelter);
        request.setType("report");
        request.setMapsdata(mapsdata);
        request.setClothname((String) clothNameComboBox.getSelectedItem());
        if(txtClothQuantity.getText().equals("")){
        request.setClothquantity(0);}
        else{
        request.setClothquantity(Integer.parseInt(txtClothQuantity.getText()));
        }
        request.setFoodname((String) foodNameComboBox.getSelectedItem());
        if(txtFoodQuantity.getText().equals("")){
                    request.setFoodquantity(0);}
        else{
        request.setFoodquantity(Integer.parseInt(txtFoodQuantity.getText()));
        }
        if(txtShelterQuantity.getText().equals("")){
                    request.setShelterquantity(0);}
        else{
        request.setShelterquantity(Integer.parseInt(txtShelterQuantity.getText()));
        }
        
        
        //test request pass
        /*ReportWorkRequest request = new ReportWorkRequest();
        request.setFirstname("Lei");
        request.setLastname("Liu");
        request.setAge(18);
        request.setHeight("180cm");
        request.setGender("male");
        request.setRace("Chinese");
        request.setCondition("Terrible");
        request.setFacenumber(11);
        
        request.setSender(userAccount);
        request.setStatus("Sent");
        */
        Organization org = null;
//        Police org1 = new Police();
       // System.out.println(enterprise);
        
        
        for (Organization organization : allorganization){
            org = null;
            if (organization instanceof Police){
                org = organization;
//                org1 = (Police) organization;
            }
            if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
//            org1.getWorkQueue().getWorkRequestList().add(request);
            
            //
            System.out.println(222);
            }
        }
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        
        JOptionPane.showMessageDialog(null, "Submit successfully!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void cbxShelterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxShelterActionPerformed
        // TODO add your handling code here:
        if(cbxShelter.isSelected()){
        labelshelterquantity.setVisible(true);
        txtShelterQuantity.setVisible(true);
        }
        else{
        labelshelterquantity.setVisible(false);
        txtShelterQuantity.setVisible(false);   
        }
        
    }//GEN-LAST:event_cbxShelterActionPerformed

    private void cbxClothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClothesActionPerformed
        // TODO add your handling code here:
        if(cbxClothes.isSelected()){
        labelclothname.setVisible(true);
        labelclothquantity.setVisible(true);
        clothNameComboBox.setVisible(true);
        txtClothQuantity.setVisible(true);}
        else{
          labelclothname.setVisible(false);
        labelclothquantity.setVisible(false);
        clothNameComboBox.setVisible(false);
        txtClothQuantity.setVisible(false);  
        }
    }//GEN-LAST:event_cbxClothesActionPerformed

    private void cbxFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFoodActionPerformed
        // TODO add your handling code here:
        if(cbxFood.isSelected()){
        labelfoodname.setVisible(true);
        txtFoodQuantity.setVisible(true);
       foodNameComboBox.setVisible(true);
       labelfoodquantity.setVisible(true);
       foodNameComboBox.setVisible(true);}
        else{
        labelfoodname.setVisible(false);
        txtFoodQuantity.setVisible(false);
       foodNameComboBox.setVisible(false);
       labelfoodquantity.setVisible(false);
       foodNameComboBox.setVisible(false);
        }
    }//GEN-LAST:event_cbxFoodActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtShelterQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShelterQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShelterQuantityActionPerformed

    private void txtClothQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClothQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClothQuantityActionPerformed

    private void txtFoodQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoodQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodQuantityActionPerformed

    private void foodNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodNameComboBoxActionPerformed
        // TODO add your handling code here:
//                String s = (String) foodageComboBox.getSelectedItem();
//        if (s != null){
//            populateFoodNameComboBox(s);
//        }
    }//GEN-LAST:event_foodNameComboBoxActionPerformed

    private void btnmapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmapActionPerformed
        // TODO add your handling code here:
        int streetnum = Integer.parseInt(txtstreetnum.getText());
        String streetname = txtstreetname.getText();
        String city = txtcity.getText();
        String state = txtstate.getText();
        String country = txtcountry.getText();
        MapsData mapsdata = new MapsData();
        mapsdata.setStreetnum(streetnum);
        mapsdata.setStreetname(streetname);
        mapsdata.setCity(city);
        mapsdata.setState(state);
        mapsdata.setCountry(country);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        try {
            userProcessContainer.add("MapsJPanel", new MapsJPanel(userProcessContainer,mapsdata));
        } catch (IOException ex) {
            Logger.getLogger(ReportJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmapActionPerformed

    private void txtClothQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClothQuantityKeyTyped
        // TODO add your handling code here:
        		int keyChar=evt.getKeyChar();
		if (keyChar>=KeyEvent.VK_0 && keyChar<=KeyEvent.VK_9) {
			
		} else {
			evt.consume();  
		}

    }//GEN-LAST:event_txtClothQuantityKeyTyped

    private void txtageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyTyped
        // TODO add your handling code here:
        int keyChar=evt.getKeyChar();
		if (keyChar>=KeyEvent.VK_0 && keyChar<=KeyEvent.VK_9) {
			
		} else {
			evt.consume();  
		}
    }//GEN-LAST:event_txtageKeyTyped

    private void txtHeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyTyped
        // TODO add your handling code here:
        int keyChar=evt.getKeyChar();
		if (keyChar>=KeyEvent.VK_0 && keyChar<=KeyEvent.VK_9) {
			
		} else {
			evt.consume();  
		}
    }//GEN-LAST:event_txtHeightKeyTyped

    private void txtFoodQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodQuantityKeyTyped
        // TODO add your handling code here:
        int keyChar=evt.getKeyChar();
		if (keyChar>=KeyEvent.VK_0 && keyChar<=KeyEvent.VK_9) {
			
		} else {
			evt.consume();  
		}
    }//GEN-LAST:event_txtFoodQuantityKeyTyped

    private void txtfacenumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfacenumberKeyTyped
        // TODO add your handling code here:
        int keyChar=evt.getKeyChar();
		if (keyChar>=KeyEvent.VK_0 && keyChar<=KeyEvent.VK_9) {
			
		} else {
			evt.consume();  
		}
    }//GEN-LAST:event_txtfacenumberKeyTyped

    private void txtShelterQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtShelterQuantityKeyTyped
        // TODO add your handling code here:
        int keyChar=evt.getKeyChar();
		if (keyChar>=KeyEvent.VK_0 && keyChar<=KeyEvent.VK_9) {
			
		} else {
			evt.consume();  
		}
    }//GEN-LAST:event_txtShelterQuantityKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnmap;
    private javax.swing.JCheckBox cbxClothes;
    private javax.swing.JCheckBox cbxFood;
    private javax.swing.JCheckBox cbxShelter;
    private javax.swing.JComboBox<String> clothNameComboBox;
    private javax.swing.JComboBox<String> conditionCBX;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JComboBox<String> foodNameComboBox;
    private javax.swing.JComboBox<String> genderCBX;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelclothname;
    private javax.swing.JLabel labelclothquantity;
    private javax.swing.JLabel labelfoodname;
    private javax.swing.JLabel labelfoodquantity;
    private javax.swing.JLabel labelshelterquantity;
    private javax.swing.JTextField txtClothQuantity;
    private javax.swing.JTextField txtFoodQuantity;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtShelterQuantity;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcountry;
    private javax.swing.JTextField txtfacenumber;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtrace;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreetname;
    private javax.swing.JTextField txtstreetnum;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
